export const YOGA_STYLES = [
  "acro",
  "aerial",
  "ashtanga",
  "beginners",
  "budokon",
  "chair",
  "children's",
  "face",
  "forrest",
  "gentle",
  "hatha",
  "hot",
  "iyengar",
  "jnana",
  "kundalini",
  "meditation",
  "pilates",
  "post-natal",
  "power",
  "pranayama",
  "pre-natal",
  "raja",
  "restorative",
  "therapy",
  "vinyasa",
  "yin",
] as const;
export type YogaStyle = typeof YOGA_STYLES[number];

export const YOGA_STYLE_EMOJI: Record<YogaStyle, string> = {
  acro: "👯",
  aerial: "🧚",
  ashtanga: "☸️",
  beginners: "🆕",
  budokon: "🥋",
  chair: "🪑",
  "children's": "👶",
  face: "🤤",
  forrest: "🌳",
  gentle: "🥰",
  hatha: "♎",
  hot: "🔥",
  iyengar: "📐",
  jnana: "🧠",
  kundalini: "🐍",
  meditation: "🧘",
  pilates: "🤸",
  "post-natal": "🤰",
  power: "💪",
  pranayama: "🌬️",
  "pre-natal": "🤰",
  raja: "👑",
  restorative: "🛌",
  therapy: "🛋️",
  vinyasa: "🍃",
  yin: "🐌",
};

const pull = [
  "alignment",
  "baby classes",
  "egyptian kemetic",
  "mom",
  "mom and baby classes",
  "nidra",
  "rocket",
];

const rename = {
  "post natal": "post-natal",
  "vinyasa flow": "vinyasa",
  "yinyasa": "yin",
};
